# -*- coding: utf-8 -*-
"""Capstone_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDc4Eoo3qy92kBh1zV_bwNO0Vffr9w9a

## **Introduction**
  The Environmental Studies field involves experts from across disciplines, ranging from Economics to Philosophy, Chemistry to Humanities, to find solutions to environmental problems. The breadth of knowledge that comes from these disciplines enables a complete analysis of a particular issue. Not only do these experts come from a variety of disciplines, but also, they come from different ethnic backgrounds. Despite Universities and Colleges across the United States pushing for higher inclusion of ethnic minorities (Asian, Hispanic/Latino, Black or African American, American Indian or Alaskan Native, Native Hawaiian or Pacific Islander), these ethnic groups are consistently underrepresented in the Environmental Studies major, despite bolstering many disciplines within the major. Even at Universities and Colleges with high percentages of ethnic minorities, they are still underrepresented in the Environmental Studies major.
  
  Trinity University is a liberal arts institution located in San Antonio, Texas that has been successful in attracting a large ethnic minority population. According to the Trinity University Factbook, in 2019-2020 ethnic minorities made up 38% of the student body on campus with only 56% of students identified as White (https://inside.trinity.edu/office-institutional-research-and-effectiveness/university-data/factbooks ). With such a diverse student body, one would expect that the Environmental Studies major (which in itself is diverse) at Trinity University would be equally or close to equally representing the proportion of ethnic minorities on campus. The Trinity University Factbook is limited to showing the overall ethnic makeup of the campus and does not have information on ethnicity for a specific major. Also, other Universities and Colleges do not have this information within their factbooks. Therefore, the purpose of this study is to determine how ethnic minority groups are represented in the Environmental Studies major.

# **Hypothesis**
Ho: There is no significant difference between the representation of ethnic minorities in the Environmental Studies major versus that of the total schools ethnic makeup.

Ha: There is a significant difference between the representation of ethnic minorities in the Environmental Studies major versus that of the total schools ethnic makeup.

# **Data**
The data comes from the "Integrated Postsecondary Education Data System (IPEDS)" database  (https://nces.ed.gov/ipeds/datacenter/). 

Colleges and Universities were selected based upon "Reference Institutions" based upon Trinity Univerity's Office of Institutional Research and Effectiveness (https://inside.trinity.edu/office-institutional-research-and-effectiveness/reference-institutions).

Data Points are broken down by ethnicity,  genders, and only from those that completed or graduated inData Points are broken down by ethnicity,  genders, and only from those that completed or graduated in the year 2017-18. Two data sets are considered, one representing the Environmental Studies majors and other representing all graduates of that year.
"""

import pandas as pd 
import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
data_envi = pd.read_csv('/content/drive/My Drive/Jasons Dataset (3) (2).csv')
data_entire = pd.read_csv('/content/drive/My Drive/Jasons Dataset Entire (2).csv')

##data_envi_observed = pd.data_envi(columns = ['White Total', 'Non White Total'])
##data_envi_observed.info()
## Create new data frame with ethnic minority(non-white and white) then combine entire and envi data. data_envi['Total_Ethnic_Minorities'] = data_envi[

"""# **Methods** 
For this analysis I am going to conduct a Chi-Square test to find the expected amount of Environmental Studies Graduates by using the school's total graduates (all majors) for that year to predict this amount.

# **Finding Expected Values**
In order to find the expected values, I divided the observed amount of "Non-White students" compared to the total graduates.
"""

data_entire.info
data_entire.head(n=32)
data_entire['Expected_Non-White'] = data_entire['Non-White Total']/ data_entire['Entire Population']
data_entire

"""Using the observed ratio between the Non-white students to total graduate population, I can determine the expected amount of Environmental Studies graduates."""

data_envi.info
data_envi.head(n=32)
data_envi['Expected_Non-White_ENVI'] = data_entire['Expected_Non-White'] * data_envi['Grand Total']
data_envi

data_envi['Observed_Non-White'] = data_envi['Non White Total']
data_envi

"""# **Chi-Squared Test**
With data of "Expected Non-White" Environmental Studies students and "Observed Non-White" Environmental Studies students, I am able to conduct a Chi-Squared Test to test if there is a stastically significant difference between observed and expected students. I found that Colagate University, Middlebury College, SMith College, and Bryn Mawr College had stastically significant results.
"""

data = ((data_envi['Expected_Non-White_ENVI'] - data_envi['Non White Total'])**2)/ data_envi['Expected_Non-White_ENVI']
data
## CVALUE 3.8

"""# **Creating Graphs**/ Results
I created bar charts to display the observed Non-White Environmental Studies Graduates with the expected. In addition, I included Trinity University, despite it not having significant results, because it is the primary University under study. Based upon a CVALUE of 3.8, these Universities and Colleges at significant differences between their observed and expected amounts of Environmental Studies Graduates in the 2017-18 school year.
 
Colgate College had the most significant difference with expected value of 6.445 and observed value of 0.
"""

data = {'Observed_Non-White': [1, 0, 12, 4, 1],
        'Expected_Non-White_ENVI': [2.719493, 6.445087, 20.843489, 9.512010, 6.590164]}
index = ['Trinity University', 'Colgate University', 'Middlebury College', 'Smith College', 'Bryn Mawr College']
df = pd.DataFrame(data=data, index=index)

df.plot.bar(stacked=False,rot=15, title='Observed for Non-White and Expected for Non-White by Significant College/University')
plt.show(block=True)

data2 = {'Total_Observed': [118],
         'Total_Expected': [178.502]}
df2= pd.DataFrame(data=data2)
df2.plot.bar(stacked=False,rot=15, title='Total Expected vs. Observed Non-White Students in ENVI')
plt.show(block=True)

"""# **Discussion and Recommendation**
The core of the Environmental Studies major surrounds the inclusion of experts from a variety of disciplines and backgrounds. According to the results of the study, the Environmental Studies major across multiple schools has an underrepresentation of ethnic minorities based upon their total ethnic makeup at the school. There are some schools such as Occidental College which meet the expected number of non-white students within the major, but for the Major across multiple schools, the numbers are not equal. It is notable that a major that relies on diversity of opinions, is not diverse in ethnicity.

This study is limited in scope to simply displaying the statistical disparity of minorities in the Environmental Studies major across multiple Institutions. Information gathered was only numerical values and is unable to be used to extrapolate on why ethnic minorities are underrepresented in the Major. In addition, Institutions were selected based upon similarity to Trinity University. It may be found that Colleges and Universities that are much larger or much smaller may have high representations of ethnic minorities, however this is outside the parameters of this study.

In general, the Institutions included in this study like Trinity University have high amounts of ethnic minority representation and push for inclusiveness of these underrepresented groups. According to Trinity University’s Diversity and Inclusion Office (DIO), their mission is “to provide programs and services that enhance the retention, persistence, and academic and career success of underrepresented and historically marginalized student populations” (https://inside.trinity.edu/get-involved/diversity-and-inclusion
). At Trinity University, they have continued to increase the ethnic minorities in their student body, however, the Environmental Studies major still lacks representation from these groups. This study is limited to displaying statistical facts about underrepresentation of these groups, but is unable to explain why there are not many within the Environmental Studies major. Further research could be done to understand the choices of students to enter certain majors compared to others, which may be useful in drawing new students towards the Environmental Studies major. On a different note, a next step could be to determine if increasing the proportion of ethnic minorities to those who are White, would lead to an increase in minorities in Environmental Studies. Currently however, it is conclusive that across the Environmental Studies major ethnic minority groups are underrepresented.
"""